name = "alcantara-cardoso-rohlfs"
compatibility_date = "2023-10-30"

# Configuração para deploy como site estático
[site]
bucket = "./" # Diretório raiz (obrigatório)
site = "alcantara-cardoso-rohlfs"

# Configurações de páginas
[site.upload]
format = "directory"

# Configuração de vinculação de domínio
[env.production]
routes = [
  { pattern = "alcantaracardosorohlfs.com", custom_domain = true }
]

[env.staging]
name = "alcantara-cardoso-rohlfs-staging"
